### ISSUE TITLE
 Could not resolve dependency

### ISSUE THREAD

**Issue by nikolas-nelson** [verto-health/ngx-turnstile#16]
Hi, having problem with dependency: 

 @angular/common@"~16.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^14.2.0" from ngx-turnstile@0.0.7
npm ERR! node_modules/ngx-turnstile
npm ERR!   ngx-turnstile@"^0.0.7" from the root project

Angular v16 NX v17 

can't use command with --force or --legacy-peer-deps because of deploy on Cloudflare. 

Thanks

**Comment by choyiny** [comment]
Investigating on a fix for Angular 16 - will update this issue when we next publish to NPM.

**Comment by choyiny** [comment]
@nikolas-nelson resolved in 0.1.0.

**Comment by AleksanderBodurri** [comment]
Hey @nikolas-nelson we just published version `0.1.0` to NPM, can you try it out?
