### ISSUE TITLE
Angular 17 compatibility

### ISSUE THREAD

**Issue by samsonkumawong** [verto-health/ngx-turnstile#18]
Hi can we please include compatibility for Angular 17 as well?

**Comment by me-marcel** [comment]
Since Angular 17 support has been recently added this issue may now be closed.

**Comment by rbalet** [comment]
@me-marcel Actually it does not as the `peerDependencies` version are set to `^v16.0.0`.

I've made a mergre-request to fix this issue

**Comment by rbalet** [comment]
@AleksanderBodurri Thx for merging it.

Could we please have a new release? :)
