### ISSUE TITLE
not working on angular 17

### ISSUE THREAD

**Issue by zakir1929** [verto-health/ngx-turnstile#21]
not working on angular 17

**Comment by me-marcel** [comment]
Would love to see the library being Angular 17 compatible as well. There seems to be a branch (see: https://github.com/verto-health/ngx-turnstile/tree/upgrade-angular-to-17) but no release for this yet. Is there maybe an ETA when the update will be published? I would like to avoid having to fork this just to update to the latestest Angular version.

**Comment by zakir1929** [comment]
can you show me the way how you did it? 
if possible a git repo of that ?

**Comment by me-marcel** [comment]
@zakir1929 I'm afraid that I cannot share the entire project. However, I prepared a repository that contains the contents of the turnstile library. 

https://github.com/me-marcel/nx-turnstile

Please keep in mind that you will need an NX monorepo with an Angular application for this library to work since it has dependencies on `@angular/*` packages.

**Comment by willfarias** [comment]
When it will be available? I think the only thing missing on  #20 is the review, right?

**Comment by me-marcel** [comment]
> When it will be available? I think the only thing missing on #20 is the review, right?

Seems like it. Linting is failing as well but that shouldn't be that big of a deal. I would love to do the review. Sadly, I can't.

**Comment by willfarias** [comment]
@cherylchen2 @AleksanderBodurri Could you help us?

**Comment by natereprogle** [comment]
FYI that PR was merged and a release was cut just now, Mend Renovate just notified me for a repo I have. This should be closed

**Comment by AleksanderBodurri** [comment]
Closed by https://github.com/verto-health/ngx-turnstile/pull/20. Thanks for the patience everyone 🙏  Let me know if there's any issues

**Comment by rbalet** [comment]
Hey @AleksanderBodurri , may you have forgotten to push a new version over on npm? '^^
