### ISSUE TITLE
Reset in Component

### ISSUE THREAD

**Issue by willfarias** [verto-health/ngx-turnstile#24]
Is there any way to use a reset method within a component?
At the moment I'm using it in an insecure way: eval("turnstile.reset()");

**Comment by choyiny** [comment]
Updating the control value to `null` will reset the component. Let me know if this works for you :)

**Comment by willfarias** [comment]
> Updating the control value to `null` will reset the component. Let me know if this works for you :)

I don't think I understood what you meant, can you post an example code?

**Comment by choyiny** [comment]
Click on "Reset Form Control" or "Set to Invalid Value" on this example page to see turnstile widget refreshing itself: https://ngx-turnstile.pages.dev/reactive-form-example

**Comment by willfarias** [comment]
@choyiny Thank you very much, I was using event binding, I changed it to formcontrol and solved it using one of the solutions in the example.
