### ISSUE TITLE
Error when installing for Angular 10

### ISSUE THREAD

**Issue by udayshetty** [verto-health/ngx-turnstile#28]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: App@1.0.85
npm ERR! Found: @angular/common@10.2.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^10.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=16.0.0" from ngx-turnstile@0.2.2
npm ERR! node_modules/ngx-turnstile
npm ERR!   ngx-turnstile@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by choyiny** [comment]
Angular 10 security updates stopped 2 years ago. This library has no plan to support an ancient version of Angular.

See: https://endoflife.date/angular

The alternative is always just to use the barebones JS library that Cloudflare has to offer. In fact, this library is just a wrapper for it !
