### ISSUE TITLE
ngAfterViewInit in SRR

### ISSUE THREAD

**Issue by zygimantas** [verto-health/ngx-turnstile#34]
```ERROR ReferenceError: window is not defined at _NgxTurnstileComponent.ngAfterViewInit```

Do you think it can be fixed by using `afterNextRender` instead? I don't expect it to work on server, just not to throw errors.

**Comment by AleksanderBodurri** [comment]
Thank you @zygimantas for reporting this. I agree with your fix for using `afterNextRender`. Will address this sometime this week and rollout a new release. Thank you for your patience 🙏
